services:
  instaswarm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: Instaswarm
    env_file:
      - .env
    volumes:
      - ${VIDEO_DOWNLOAD_PATH_ON_HOST}:/app/video
    ports:
      - "5000:8080"
      - "5001:8081"
    restart: on-failure
